micronaut:
  application:
    name: mnSuperapp
  caches:
    my-cache:
      maximumSize: 20
  session:
    http:
      cookie: true
      header: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
    - access: isAnonymous()
      pattern: /swagger/**
    - access: isAnonymous()
      pattern: /swagger-ui/**
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
netty:
  default:
    allocator:
      max-order: 3
dataSource:
  url: jdbc:mysql://localhost:3306/db
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: ''
  pooled: true
  jmxExport: true
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
kafka.bootstrap.servers: localhost:9092
